spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///D:/pulivarthi/2024/login/config-map
            - file:///D:/pulivarthi/2024/order-service/config-map
          addLabelLocations: false