spring:
  config:
    activate:
      on-profile: aws-prod
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/saradhiparthu/spring-cloud-config-data
          search-paths: config
          basedir: config-map
          default-label: master
          repos:
            login-service:
              clone-on-start: true
              uri: https://github.com/saradhiparthu/spring-cloud-config-data
              search-paths: config
              basedir: config-map
              default-label: master
            