spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/your-username/config-repo-1
            default-label: main
          - type: git
            uri: https://gitlab.com/your-username/config-repo-2
            default-label: main
          - type: file
            search-locations: file:///path/to/local/config